[project]
name = "check-tf-module"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "packaging>=25.0",
    "python-hcl2>=7.2.1",
    "requests>=2.32.4",
]
